#!/usr/bin/env python3
"""Package the synthetic Nepali plate corpus for upload as a private Kaggle Dataset.

`datasets/plates/gen_plates.py` writes images and PaddleOCR-format recognition
labels to a local directory (never committed — DATASET_SPEC.md section 6.5,
`.gitignore`). This script builds the folder `kaggle datasets create` expects:
a flat copy of the images, the train/val label files, the charset, and a
`dataset-metadata.json` manifest.

This script does NOT call the Kaggle API and does NOT upload anything — the
plan is explicit that the orchestrator runs the actual `kaggle datasets
create` command later, with credentials this environment does not have.

    python datasets/plates/gen_plates.py --count 20500 --out /path/to/scratch/plates
    python edge/anpr/scripts/package_plates_for_kaggle.py \\
        --source /path/to/scratch/plates \\
        --out edge/anpr/kaggle_upload \\
        --owner <your-kaggle-username>

Then, elsewhere, with Kaggle credentials configured:
    kaggle datasets create -p edge/anpr/kaggle_upload --dir-mode zip
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent


def log(level: str, message: str, **fields) -> None:
    stamp = time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime())
    extra = " ".join(f"{k}={v}" for k, v in fields.items())
    line = f"{stamp} {level:<5} package_for_kaggle | {message}"
    if extra:
        line = f"{line} | {extra}"
    print(line, file=sys.stderr if level in ("ERROR", "FATAL") else sys.stdout, flush=True)


def _resolve_image(images_dir: Path, rel_path: str) -> Path | None:
    """gen_plates.py labels every row 'out/images/<name>.jpg' regardless of --out."""
    candidates = [images_dir / rel_path, images_dir / Path(rel_path).name]
    if rel_path.startswith("out/"):
        candidates.append(images_dir.parent / rel_path)
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


def copy_split(label_file: Path, source_root: Path, dest_images: Path) -> int:
    if not label_file.is_file():
        raise SystemExit(f"missing label file: {label_file}")
    dest_images.mkdir(parents=True, exist_ok=True)
    copied = 0
    with label_file.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line:
                continue
            rel_path, _, _text = line.partition("\t")
            src = _resolve_image(source_root / "images", rel_path) or _resolve_image(source_root, rel_path)
            if src is None:
                log("WARN", "image not found, skipped", rel_path=rel_path)
                continue
            shutil.copy2(src, dest_images / Path(rel_path).name)
            copied += 1
    return copied


def rewrite_labels_flat(label_file: Path, dest_label_file: Path, flat_prefix: str) -> None:
    """Rewrite label paths to the flat layout this package uses (images/<name>.jpg)."""
    lines_out = []
    for line in label_file.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        rel_path, _, text = line.partition("\t")
        lines_out.append(f"{flat_prefix}/{Path(rel_path).name}\t{text}")
    dest_label_file.write_text("\n".join(lines_out) + "\n", encoding="utf-8")


def write_manifest(out_dir: Path, owner: str, title: str, license_name: str, sample_count: int) -> Path:
    slug = title.lower().replace(" ", "-")
    manifest = {
        "title": title,
        "id": f"{owner}/{slug}" if owner else slug,
        "licenses": [{"name": license_name}],
        "description": (
            "Synthetic Nepali licence plates for PP-OCRv5 Devanagari recognition fine-tuning. "
            "Generated by datasets/plates/gen_plates.py + degrade.py "
            "(TRUEWATCH, SIH26187). Rendered text is OFL-1.1 (Noto Sans Devanagari font); "
            f"{sample_count} labelled samples. See DATASET_SPEC.md section 6 in the source "
            "repository for the full generation and degradation spec."
        ),
    }
    path = out_dir / "dataset-metadata.json"
    path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", required=True, help="the --out directory gen_plates.py wrote to")
    ap.add_argument("--labels", default=None, help="labels dir; default <source>/labels")
    ap.add_argument("--out", default=str(HERE.parent / "kaggle_upload"), help="package output directory")
    ap.add_argument("--owner", default="", help="Kaggle username, used to form the dataset id")
    ap.add_argument("--title", default="truewatch-nepali-plates-synthetic")
    ap.add_argument("--license", default="CC0-1.0", help="license name for dataset-metadata.json")
    args = ap.parse_args()

    source_root = Path(args.source).resolve()
    labels_dir = Path(args.labels).resolve() if args.labels else source_root / "labels"
    out_dir = Path(args.out).resolve()
    if out_dir.exists():
        shutil.rmtree(out_dir)
    images_out = out_dir / "images"

    train_count = copy_split(labels_dir / "rec_gt_train.txt", source_root, images_out)
    val_count = copy_split(labels_dir / "rec_gt_val.txt", source_root, images_out)
    log("INFO", "images copied", train=train_count, val=val_count)

    rewrite_labels_flat(labels_dir / "rec_gt_train.txt", out_dir / "rec_gt_train.txt", "images")
    rewrite_labels_flat(labels_dir / "rec_gt_val.txt", out_dir / "rec_gt_val.txt", "images")
    shutil.copy2(labels_dir / "charset.txt", out_dir / "charset.txt")
    if (labels_dir / "summary.json").is_file():
        shutil.copy2(labels_dir / "summary.json", out_dir / "summary.json")

    manifest_path = write_manifest(out_dir, args.owner, args.title, args.license, train_count + val_count)
    log("INFO", "dataset-metadata.json written", path=str(manifest_path))
    log(
        "INFO",
        "package ready",
        out=str(out_dir),
        next_step="kaggle datasets create -p " + str(out_dir) + " --dir-mode zip",
    )
    if train_count + val_count < 20000:
        log("WARN", "packaged sample count is below the 20,000 gate G17 requires", have=train_count + val_count)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
